### ISSUE TITLE
Wrong Z position when using relative movements

### ISSUE THREAD

**Issue by asciipip** [agrif/OctoPrint-InfluxDB#30]
When a print's gcode includes relative movements, those relative movements are written to InfluxDB as if they were absolute values.

Here's the specific behavior I'm seeing:

I'm using OctoLapse to record timelapses of my prints. I have OctoLapse set to Z-hop the hotend up 0.4 mm before moving it out of the way for each photo, to prevent the nozzle from dragging across existing lines. OctoLapse does this by inserting relative movements into the gcode stream. In my case, that means sending `G91`, `G1 Z0.400`, moving to the snapshot location, moving back, and sending `G1 Z-0.400`, `G90` (the last because my prints otherwise use absolute positioning).

That shows up in the InfluxDB database like this:

    > SELECT current_z FROM progress WHERE time > '2024-10-18T14:03:20Z' and time < '2024-10-18T14:03:26Z'
    name: progress
    time                        current_z
    ----                        ---------
    2024-10-18T14:03:20.40794Z  6
    2024-10-18T14:03:20.631068Z 6
    2024-10-18T14:03:22.798683Z 0.4
    2024-10-18T14:03:22.842193Z 0.4
    2024-10-18T14:03:23.929142Z 0.4
    2024-10-18T14:03:24.002798Z 0.4
    2024-10-18T14:03:25.157071Z -0.4
    2024-10-18T14:03:25.200298Z -0.4

During this time window, I should instead be seeing sequential Z values of 6.0, 6.4, and 6.0, because that's where the hotend was actually positioned.

**Comment by agrif** [comment]
This is surprising to me, as [the plugin simply reads the `currentZ` field](https://github.com/agrif/OctoPrint-InfluxDB/blob/aa7e498e292204e5f08b4edaeadc7245c920c21b/octoprint_influxdb/__init__.py#L284).

Doing some digging, it looks like this is an old relic in OctoPrint, and right now OctoPrint avoids tracking the location [for some pretty compelling reasons](https://community.octoprint.org/t/why-doesnt-octoprint-show-me-the-current-hotend-position-anywhere/232). I used to think I should add a state tracker to this plugin for info like this, but having read that FAQ, I think I agree that's the wrong solution.

It might make sense to query the printer periodically for this info to send to Influx. This would be a somewhat big change, since right now all the plugin does is shuffle data from OctoPrint to Influx without any active querying.

**Comment by asciipip** [comment]
That's all fair enough.  I think I could make an argument for simplistic state tracking with the acceptance of the caveats (possible non-OctoPrint-initiated moves, exceeding the printer's physical bounds), but that'd be an argument for the OctoPrint developers and probably ought to be accompanied by working code.

But is it possible for this plugin to save an additional field indicating whether the printer is in absolute or relative mode?  If I had that, I could probably reconstruct the absolute values I'd like to see.  (Not easily, but at least it'd be possible.)

**Comment by asciipip** [comment]
Well, I found a workaround. The `progress` metric has the literal last Z value from the gcode, regardless of whether it's in absolute or relative mode. But the `PositionUpdate` event, in the `events` metric, has a `z` value that represents OctoPrint's best estimate of the current Z coordinate, regardless of the combination of absolute and relative movements that got it there.

Since the data I want—even considering all the caveats—is present in the data stored by the plugin, I can work with it.

**Comment by agrif** [comment]
Glad to hear you found something. I'll try to remember this if other folks show up wanting the same thing.
